<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobcardCategory extends Model
{
    protected $guarded = [];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($cat){
            $relationsMethods = ['category'];
            foreach ($relationsMethods as $relationsMethod){
                if ($cat->$relationsMethod()->count() > 0){
                    return false;
                }
            }
        });
    }
    public function category()
    {
        return $this->belongsTo(JobcardCategory::class,'id');
    }

    public function transaction_types()
    {
        return $this->belongsToMany(Transaction::class,'jobcard_category_transaction');
    }

    public function inv_item()
    {
        return $this->belongsTo(Transaction::class,'inv_tr_id','transaction_id');
    }

     public function stk_item()
    {
        return $this->belongsTo(Transaction::class,'stk_tr_id','transaction_id');
    }
}
